/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'

// Create Virtual Routes

const UsersLazyImport = createFileRoute('/users')()
const TaskLazyImport = createFileRoute('/task')()
const StoresLazyImport = createFileRoute('/stores')()
const ProductsLazyImport = createFileRoute('/products')()
const OrdersLazyImport = createFileRoute('/orders')()
const InventoryLazyImport = createFileRoute('/inventory')()
const IdolsLazyImport = createFileRoute('/idols')()
const FinanceLazyImport = createFileRoute('/finance')()
const CalendarLazyImport = createFileRoute('/calendar')()
const IndexLazyImport = createFileRoute('/')()
const UsersUserIdLazyImport = createFileRoute('/users/$userId')()
const StoresStoreIdLazyImport = createFileRoute('/stores/$storeId')()
const IdolsTeamIdLazyImport = createFileRoute('/idols/$teamId')()

// Create/Update Routes

const UsersLazyRoute = UsersLazyImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/users.lazy').then((d) => d.Route))

const TaskLazyRoute = TaskLazyImport.update({
  id: '/task',
  path: '/task',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/task.lazy').then((d) => d.Route))

const StoresLazyRoute = StoresLazyImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/stores.lazy').then((d) => d.Route))

const ProductsLazyRoute = ProductsLazyImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/products.lazy').then((d) => d.Route))

const OrdersLazyRoute = OrdersLazyImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/orders.lazy').then((d) => d.Route))

const InventoryLazyRoute = InventoryLazyImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/inventory.lazy').then((d) => d.Route))

const IdolsLazyRoute = IdolsLazyImport.update({
  id: '/idols',
  path: '/idols',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/idols.lazy').then((d) => d.Route))

const FinanceLazyRoute = FinanceLazyImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/finance.lazy').then((d) => d.Route))

const CalendarLazyRoute = CalendarLazyImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/calendar.lazy').then((d) => d.Route))

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const UsersUserIdLazyRoute = UsersUserIdLazyImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => UsersLazyRoute,
} as any).lazy(() => import('./routes/users.$userId.lazy').then((d) => d.Route))

const StoresStoreIdLazyRoute = StoresStoreIdLazyImport.update({
  id: '/$storeId',
  path: '/$storeId',
  getParentRoute: () => StoresLazyRoute,
} as any).lazy(() =>
  import('./routes/stores.$storeId.lazy').then((d) => d.Route),
)

const IdolsTeamIdLazyRoute = IdolsTeamIdLazyImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => IdolsLazyRoute,
} as any).lazy(() => import('./routes/idols.$teamId.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarLazyImport
      parentRoute: typeof rootRoute
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceLazyImport
      parentRoute: typeof rootRoute
    }
    '/idols': {
      id: '/idols'
      path: '/idols'
      fullPath: '/idols'
      preLoaderRoute: typeof IdolsLazyImport
      parentRoute: typeof rootRoute
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryLazyImport
      parentRoute: typeof rootRoute
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersLazyImport
      parentRoute: typeof rootRoute
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsLazyImport
      parentRoute: typeof rootRoute
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresLazyImport
      parentRoute: typeof rootRoute
    }
    '/task': {
      id: '/task'
      path: '/task'
      fullPath: '/task'
      preLoaderRoute: typeof TaskLazyImport
      parentRoute: typeof rootRoute
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersLazyImport
      parentRoute: typeof rootRoute
    }
    '/idols/$teamId': {
      id: '/idols/$teamId'
      path: '/$teamId'
      fullPath: '/idols/$teamId'
      preLoaderRoute: typeof IdolsTeamIdLazyImport
      parentRoute: typeof IdolsLazyImport
    }
    '/stores/$storeId': {
      id: '/stores/$storeId'
      path: '/$storeId'
      fullPath: '/stores/$storeId'
      preLoaderRoute: typeof StoresStoreIdLazyImport
      parentRoute: typeof StoresLazyImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdLazyImport
      parentRoute: typeof UsersLazyImport
    }
  }
}

// Create and export the route tree

interface IdolsLazyRouteChildren {
  IdolsTeamIdLazyRoute: typeof IdolsTeamIdLazyRoute
}

const IdolsLazyRouteChildren: IdolsLazyRouteChildren = {
  IdolsTeamIdLazyRoute: IdolsTeamIdLazyRoute,
}

const IdolsLazyRouteWithChildren = IdolsLazyRoute._addFileChildren(
  IdolsLazyRouteChildren,
)

interface StoresLazyRouteChildren {
  StoresStoreIdLazyRoute: typeof StoresStoreIdLazyRoute
}

const StoresLazyRouteChildren: StoresLazyRouteChildren = {
  StoresStoreIdLazyRoute: StoresStoreIdLazyRoute,
}

const StoresLazyRouteWithChildren = StoresLazyRoute._addFileChildren(
  StoresLazyRouteChildren,
)

interface UsersLazyRouteChildren {
  UsersUserIdLazyRoute: typeof UsersUserIdLazyRoute
}

const UsersLazyRouteChildren: UsersLazyRouteChildren = {
  UsersUserIdLazyRoute: UsersUserIdLazyRoute,
}

const UsersLazyRouteWithChildren = UsersLazyRoute._addFileChildren(
  UsersLazyRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginRoute
  '/calendar': typeof CalendarLazyRoute
  '/finance': typeof FinanceLazyRoute
  '/idols': typeof IdolsLazyRouteWithChildren
  '/inventory': typeof InventoryLazyRoute
  '/orders': typeof OrdersLazyRoute
  '/products': typeof ProductsLazyRoute
  '/stores': typeof StoresLazyRouteWithChildren
  '/task': typeof TaskLazyRoute
  '/users': typeof UsersLazyRouteWithChildren
  '/idols/$teamId': typeof IdolsTeamIdLazyRoute
  '/stores/$storeId': typeof StoresStoreIdLazyRoute
  '/users/$userId': typeof UsersUserIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginRoute
  '/calendar': typeof CalendarLazyRoute
  '/finance': typeof FinanceLazyRoute
  '/idols': typeof IdolsLazyRouteWithChildren
  '/inventory': typeof InventoryLazyRoute
  '/orders': typeof OrdersLazyRoute
  '/products': typeof ProductsLazyRoute
  '/stores': typeof StoresLazyRouteWithChildren
  '/task': typeof TaskLazyRoute
  '/users': typeof UsersLazyRouteWithChildren
  '/idols/$teamId': typeof IdolsTeamIdLazyRoute
  '/stores/$storeId': typeof StoresStoreIdLazyRoute
  '/users/$userId': typeof UsersUserIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/login': typeof LoginRoute
  '/calendar': typeof CalendarLazyRoute
  '/finance': typeof FinanceLazyRoute
  '/idols': typeof IdolsLazyRouteWithChildren
  '/inventory': typeof InventoryLazyRoute
  '/orders': typeof OrdersLazyRoute
  '/products': typeof ProductsLazyRoute
  '/stores': typeof StoresLazyRouteWithChildren
  '/task': typeof TaskLazyRoute
  '/users': typeof UsersLazyRouteWithChildren
  '/idols/$teamId': typeof IdolsTeamIdLazyRoute
  '/stores/$storeId': typeof StoresStoreIdLazyRoute
  '/users/$userId': typeof UsersUserIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/calendar'
    | '/finance'
    | '/idols'
    | '/inventory'
    | '/orders'
    | '/products'
    | '/stores'
    | '/task'
    | '/users'
    | '/idols/$teamId'
    | '/stores/$storeId'
    | '/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/calendar'
    | '/finance'
    | '/idols'
    | '/inventory'
    | '/orders'
    | '/products'
    | '/stores'
    | '/task'
    | '/users'
    | '/idols/$teamId'
    | '/stores/$storeId'
    | '/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/calendar'
    | '/finance'
    | '/idols'
    | '/inventory'
    | '/orders'
    | '/products'
    | '/stores'
    | '/task'
    | '/users'
    | '/idols/$teamId'
    | '/stores/$storeId'
    | '/users/$userId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LoginRoute: typeof LoginRoute
  CalendarLazyRoute: typeof CalendarLazyRoute
  FinanceLazyRoute: typeof FinanceLazyRoute
  IdolsLazyRoute: typeof IdolsLazyRouteWithChildren
  InventoryLazyRoute: typeof InventoryLazyRoute
  OrdersLazyRoute: typeof OrdersLazyRoute
  ProductsLazyRoute: typeof ProductsLazyRoute
  StoresLazyRoute: typeof StoresLazyRouteWithChildren
  TaskLazyRoute: typeof TaskLazyRoute
  UsersLazyRoute: typeof UsersLazyRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LoginRoute: LoginRoute,
  CalendarLazyRoute: CalendarLazyRoute,
  FinanceLazyRoute: FinanceLazyRoute,
  IdolsLazyRoute: IdolsLazyRouteWithChildren,
  InventoryLazyRoute: InventoryLazyRoute,
  OrdersLazyRoute: OrdersLazyRoute,
  ProductsLazyRoute: ProductsLazyRoute,
  StoresLazyRoute: StoresLazyRouteWithChildren,
  TaskLazyRoute: TaskLazyRoute,
  UsersLazyRoute: UsersLazyRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/calendar",
        "/finance",
        "/idols",
        "/inventory",
        "/orders",
        "/products",
        "/stores",
        "/task",
        "/users"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/calendar": {
      "filePath": "calendar.lazy.tsx"
    },
    "/finance": {
      "filePath": "finance.lazy.tsx"
    },
    "/idols": {
      "filePath": "idols.lazy.tsx",
      "children": [
        "/idols/$teamId"
      ]
    },
    "/inventory": {
      "filePath": "inventory.lazy.tsx"
    },
    "/orders": {
      "filePath": "orders.lazy.tsx"
    },
    "/products": {
      "filePath": "products.lazy.tsx"
    },
    "/stores": {
      "filePath": "stores.lazy.tsx",
      "children": [
        "/stores/$storeId"
      ]
    },
    "/task": {
      "filePath": "task.lazy.tsx"
    },
    "/users": {
      "filePath": "users.lazy.tsx",
      "children": [
        "/users/$userId"
      ]
    },
    "/idols/$teamId": {
      "filePath": "idols.$teamId.lazy.tsx",
      "parent": "/idols"
    },
    "/stores/$storeId": {
      "filePath": "stores.$storeId.lazy.tsx",
      "parent": "/stores"
    },
    "/users/$userId": {
      "filePath": "users.$userId.lazy.tsx",
      "parent": "/users"
    }
  }
}
ROUTE_MANIFEST_END */
