/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login-lova'
import { Route as IdolsIndexImport } from './routes/admin/idols.index'

// Create Virtual Routes

const TaskLazyImport = createFileRoute('/admin/task')()
const SettingsLazyImport = createFileRoute('/admin/settings')()
const ProductsLazyImport = createFileRoute('/admin/products')()
const PolicyLazyImport = createFileRoute('/admin/policy')()
const OrdersLazyImport = createFileRoute('/admin/orders')()
const InventoryLazyImport = createFileRoute('/admin/inventory')()
const FinanceLazyImport = createFileRoute('/admin/finance')()
const FaqLazyImport = createFileRoute('/admin/faq')()
const CalendarLazyImport = createFileRoute('/admin/calendar')()
const IndexLazyImport = createFileRoute('/admin/')()
const UsersIndexLazyImport = createFileRoute('/admin/users/')()
const StoresIndexLazyImport = createFileRoute('/admin/stores/')()
const UsersUserIdLazyImport = createFileRoute('/admin/users/$userId')()
const StoresStoreIdLazyImport = createFileRoute('/admin/stores/$storeId')()
const IdolsTeamIdLazyImport = createFileRoute('/admin/idols/$teamId')()

// Create/Update Routes

const TaskLazyRoute = TaskLazyImport.update({
    id: '/admin/task',
    path: '/admin/task',
    getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/admin/task.lazy').then((d) => d.Route))

const SettingsLazyRoute = SettingsLazyImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/admin/settings.lazy').then((d) => d.Route))

const ProductsLazyRoute = ProductsLazyImport.update({
    id: '/admin/products',
    path: '/admin/products',
    getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/admin/products.lazy').then((d) => d.Route))

const PolicyLazyRoute = PolicyLazyImport.update({
    id: '/admin/policy',
    path: '/admin/policy',
    getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/admin/policy.lazy').then((d) => d.Route))

const OrdersLazyRoute = OrdersLazyImport.update({
    id: '/admin/orders',
    path: '/admin/orders',
    getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/admin/orders.lazy').then((d) => d.Route))

const InventoryLazyRoute = InventoryLazyImport.update({
    id: '/admin/inventory',
    path: '/admin/inventory',
    getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/admin/inventory.lazy').then((d) => d.Route))

const FinanceLazyRoute = FinanceLazyImport.update({
    id: '/admin/finance',
    path: '/admin/finance',
    getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/admin/finance.lazy').then((d) => d.Route))

const FaqLazyRoute = FaqLazyImport.update({
    id: '/admin/faq',
    path: '/admin/faq',
    getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/admin/faq.lazy').then((d) => d.Route))

const CalendarLazyRoute = CalendarLazyImport.update({
    id: '/admin/calendar',
    path: '/admin/calendar',
    getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/admin/calendar.lazy').then((d) => d.Route))

const LoginRoute = LoginImport.update({
    id: '/login-lova',
    path: '/login-lova',
    getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/admin/index.lazy').then((d) => d.Route))

const UsersIndexLazyRoute = UsersIndexLazyImport.update({
    id: '/admin/users/',
    path: '/admin/users/',
    getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/admin/users.index.lazy').then((d) => d.Route))

const StoresIndexLazyRoute = StoresIndexLazyImport.update({
    id: '/admin/stores/',
    path: '/admin/stores/',
    getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/admin/stores.index.lazy').then((d) => d.Route))

const IdolsIndexRoute = IdolsIndexImport.update({
    id: '/admin/idols/',
    path: '/admin/idols/',
    getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/admin/idols.index.lazy').then((d) => d.Route))

const UsersUserIdLazyRoute = UsersUserIdLazyImport.update({
    id: '/admin/users/$userId',
    path: '/admin/users/$userId',
    getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/admin/users.$userId.lazy').then((d) => d.Route))

const StoresStoreIdLazyRoute = StoresStoreIdLazyImport.update({
    id: '/admin/stores/$storeId',
    path: '/admin/stores/$storeId',
    getParentRoute: () => rootRoute,
} as any).lazy(() =>
    import('./routes/admin/stores.$storeId.lazy').then((d) => d.Route),
)

const IdolsTeamIdLazyRoute = IdolsTeamIdLazyImport.update({
    id: '/admin/idols/$teamId',
    path: '/admin/idols/$teamId',
    getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/admin/idols.$teamId.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/admin/': {
            id: '/admin/'
            path: '/admin/'
            fullPath: '/admin/'
            preLoaderRoute: typeof IndexLazyImport
            parentRoute: typeof rootRoute
        }
        '/login-lova': {
            id: '/login-lova'
            path: '/login-lova'
            fullPath: '/login-lova'
            preLoaderRoute: typeof LoginImport
            parentRoute: typeof rootRoute
        }
        '/admin/calendar': {
            id: '/admin/calendar'
            path: '/admin/calendar'
            fullPath: '/admin/calendar'
            preLoaderRoute: typeof CalendarLazyImport
            parentRoute: typeof rootRoute
        }
        '/admin/faq': {
            id: '/admin/faq'
            path: '/admin/faq'
            fullPath: '/admin/faq'
            preLoaderRoute: typeof FaqLazyImport
            parentRoute: typeof rootRoute
        }
        '/admin/finance': {
            id: '/admin/finance'
            path: '/admin/finance'
            fullPath: '/admin/finance'
            preLoaderRoute: typeof FinanceLazyImport
            parentRoute: typeof rootRoute
        }
        '/admin/inventory': {
            id: '/admin/inventory'
            path: '/admin/inventory'
            fullPath: '/admin/inventory'
            preLoaderRoute: typeof InventoryLazyImport
            parentRoute: typeof rootRoute
        }
        '/admin/orders': {
            id: '/admin/orders'
            path: '/admin/orders'
            fullPath: '/admin/orders'
            preLoaderRoute: typeof OrdersLazyImport
            parentRoute: typeof rootRoute
        }
        '/admin/policy': {
            id: '/admin/policy'
            path: '/admin/policy'
            fullPath: '/admin/policy'
            preLoaderRoute: typeof PolicyLazyImport
            parentRoute: typeof rootRoute
        }
        '/admin/products': {
            id: '/admin/products'
            path: '/admin/products'
            fullPath: '/admin/products'
            preLoaderRoute: typeof ProductsLazyImport
            parentRoute: typeof rootRoute
        }
        '/admin/settings': {
            id: '/admin/settings'
            path: '/admin/settings'
            fullPath: '/admin/settings'
            preLoaderRoute: typeof SettingsLazyImport
            parentRoute: typeof rootRoute
        }
        '/admin/task': {
            id: '/admin/task'
            path: '/admin/task'
            fullPath: '/admin/task'
            preLoaderRoute: typeof TaskLazyImport
            parentRoute: typeof rootRoute
        }
        '/admin/idols/$teamId': {
            id: '/admin/idols/$teamId'
            path: '/admin/idols/$teamId'
            fullPath: '/admin/idols/$teamId'
            preLoaderRoute: typeof IdolsTeamIdLazyImport
            parentRoute: typeof rootRoute
        }
        '/admin/stores/$storeId': {
            id: '/admin/stores/$storeId'
            path: '/admin/stores/$storeId'
            fullPath: '/admin/stores/$storeId'
            preLoaderRoute: typeof StoresStoreIdLazyImport
            parentRoute: typeof rootRoute
        }
        '/admin/users/$userId': {
            id: '/admin/users/$userId'
            path: '/admin/users/$userId'
            fullPath: '/admin/users/$userId'
            preLoaderRoute: typeof UsersUserIdLazyImport
            parentRoute: typeof rootRoute
        }
        '/admin/idols/': {
            id: '/admin/idols/'
            path: '/admin/idols'
            fullPath: '/admin/idols'
            preLoaderRoute: typeof IdolsIndexImport
            parentRoute: typeof rootRoute
        }
        '/admin/stores/': {
            id: '/admin/stores/'
            path: '/admin/stores'
            fullPath: '/admin/stores'
            preLoaderRoute: typeof StoresIndexLazyImport
            parentRoute: typeof rootRoute
        }
        '/admin/users/': {
            id: '/admin/users/'
            path: '/admin/users'
            fullPath: '/admin/users'
            preLoaderRoute: typeof UsersIndexLazyImport
            parentRoute: typeof rootRoute
        }
    }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
    '/admin/': typeof IndexLazyRoute
    '/login-lova': typeof LoginRoute
    '/admin/calendar': typeof CalendarLazyRoute
    '/admin/faq': typeof FaqLazyRoute
    '/admin/finance': typeof FinanceLazyRoute
    '/admin/inventory': typeof InventoryLazyRoute
    '/admin/orders': typeof OrdersLazyRoute
    '/admin/policy': typeof PolicyLazyRoute
    '/admin/products': typeof ProductsLazyRoute
    '/admin/settings': typeof SettingsLazyRoute
    '/admin/task': typeof TaskLazyRoute
    '/admin/idols/$teamId': typeof IdolsTeamIdLazyRoute
    '/admin/stores/$storeId': typeof StoresStoreIdLazyRoute
    '/admin/users/$userId': typeof UsersUserIdLazyRoute
    '/admin/idols': typeof IdolsIndexRoute
    '/admin/stores': typeof StoresIndexLazyRoute
    '/admin/users': typeof UsersIndexLazyRoute
}

export interface FileRoutesByTo {
    '/admin/': typeof IndexLazyRoute
    '/login-lova': typeof LoginRoute
    '/admin/calendar': typeof CalendarLazyRoute
    '/admin/faq': typeof FaqLazyRoute
    '/admin/finance': typeof FinanceLazyRoute
    '/admin/inventory': typeof InventoryLazyRoute
    '/admin/orders': typeof OrdersLazyRoute
    '/admin/policy': typeof PolicyLazyRoute
    '/admin/products': typeof ProductsLazyRoute
    '/admin/settings': typeof SettingsLazyRoute
    '/admin/task': typeof TaskLazyRoute
    '/admin/idols/$teamId': typeof IdolsTeamIdLazyRoute
    '/admin/stores/$storeId': typeof StoresStoreIdLazyRoute
    '/admin/users/$userId': typeof UsersUserIdLazyRoute
    '/admin/idols': typeof IdolsIndexRoute
    '/admin/stores': typeof StoresIndexLazyRoute
    '/admin/users': typeof UsersIndexLazyRoute
}

export interface FileRoutesById {
    __root__: typeof rootRoute
    '/admin/': typeof IndexLazyRoute
    '/login-lova': typeof LoginRoute
    '/admin/calendar': typeof CalendarLazyRoute
    '/admin/faq': typeof FaqLazyRoute
    '/admin/finance': typeof FinanceLazyRoute
    '/admin/inventory': typeof InventoryLazyRoute
    '/admin/orders': typeof OrdersLazyRoute
    '/admin/policy': typeof PolicyLazyRoute
    '/admin/products': typeof ProductsLazyRoute
    '/admin/settings': typeof SettingsLazyRoute
    '/admin/task': typeof TaskLazyRoute
    '/admin/idols/$teamId': typeof IdolsTeamIdLazyRoute
    '/admin/stores/$storeId': typeof StoresStoreIdLazyRoute
    '/admin/users/$userId': typeof UsersUserIdLazyRoute
    '/admin/idols/': typeof IdolsIndexRoute
    '/admin/stores/': typeof StoresIndexLazyRoute
    '/admin/users/': typeof UsersIndexLazyRoute
}

export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath
    fullPaths:
    | '/admin/'
    | '/login-lova'
    | '/admin/calendar'
    | '/admin/faq'
    | '/admin/finance'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/policy'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/task'
    | '/admin/idols/$teamId'
    | '/admin/stores/$storeId'
    | '/admin/users/$userId'
    | '/admin/idols'
    | '/admin/stores'
    | '/admin/users'
    fileRoutesByTo: FileRoutesByTo
    to:
    | '/admin/'
    | '/login-lova'
    | '/admin/calendar'
    | '/admin/faq'
    | '/admin/finance'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/policy'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/task'
    | '/admin/idols/$teamId'
    | '/admin/stores/$storeId'
    | '/admin/users/$userId'
    | '/admin/idols'
    | '/admin/stores'
    | '/admin/users'
    id:
    | '__root__'
    | '/admin/'
    | '/login-lova'
    | '/admin/calendar'
    | '/admin/faq'
    | '/admin/finance'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/policy'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/task'
    | '/admin/idols/$teamId'
    | '/admin/stores/$storeId'
    | '/admin/users/$userId'
    | '/admin/idols/'
    | '/admin/stores/'
    | '/admin/users/'
    fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
    IndexLazyRoute: typeof IndexLazyRoute
    LoginRoute: typeof LoginRoute
    CalendarLazyRoute: typeof CalendarLazyRoute
    FaqLazyRoute: typeof FaqLazyRoute
    FinanceLazyRoute: typeof FinanceLazyRoute
    InventoryLazyRoute: typeof InventoryLazyRoute
    OrdersLazyRoute: typeof OrdersLazyRoute
    PolicyLazyRoute: typeof PolicyLazyRoute
    ProductsLazyRoute: typeof ProductsLazyRoute
    SettingsLazyRoute: typeof SettingsLazyRoute
    TaskLazyRoute: typeof TaskLazyRoute
    IdolsTeamIdLazyRoute: typeof IdolsTeamIdLazyRoute
    StoresStoreIdLazyRoute: typeof StoresStoreIdLazyRoute
    UsersUserIdLazyRoute: typeof UsersUserIdLazyRoute
    IdolsIndexRoute: typeof IdolsIndexRoute
    StoresIndexLazyRoute: typeof StoresIndexLazyRoute
    UsersIndexLazyRoute: typeof UsersIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
    IndexLazyRoute: IndexLazyRoute,
    LoginRoute: LoginRoute,
    CalendarLazyRoute: CalendarLazyRoute,
    FaqLazyRoute: FaqLazyRoute,
    FinanceLazyRoute: FinanceLazyRoute,
    InventoryLazyRoute: InventoryLazyRoute,
    OrdersLazyRoute: OrdersLazyRoute,
    PolicyLazyRoute: PolicyLazyRoute,
    ProductsLazyRoute: ProductsLazyRoute,
    SettingsLazyRoute: SettingsLazyRoute,
    TaskLazyRoute: TaskLazyRoute,
    IdolsTeamIdLazyRoute: IdolsTeamIdLazyRoute,
    StoresStoreIdLazyRoute: StoresStoreIdLazyRoute,
    UsersUserIdLazyRoute: UsersUserIdLazyRoute,
    IdolsIndexRoute: IdolsIndexRoute,
    StoresIndexLazyRoute: StoresIndexLazyRoute,
    UsersIndexLazyRoute: UsersIndexLazyRoute,
}

export const routeTree = rootRoute
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/admin/",
        "/login-lova",
        "/admin/calendar",
        "/admin/faq",
        "/admin/finance",
        "/admin/inventory",
        "/admin/orders",
        "/admin/policy",
        "/admin/products",
        "/admin/settings",
        "/admin/task",
        "/admin/idols/$teamId",
        "/admin/stores/$storeId",
        "/admin/users/$userId",
        "/admin/idols/",
        "/admin/stores/",
        "/admin/users/"
      ]
    },
    "/admin/": {
      "filePath": "admin/index.lazy.tsx"
    },
    "/login-lova": {
      "filePath": "login-lova.tsx"
    },
    "/admin/calendar": {
      "filePath": "admin/calendar.lazy.tsx"
    },
    "/admin/faq": {
      "filePath": "admin/faq.lazy.tsx"
    },
    "/admin/finance": {
      "filePath": "admin/finance.lazy.tsx"
    },
    "/admin/inventory": {
      "filePath": "admin/inventory.lazy.tsx"
    },
    "/admin/orders": {
      "filePath": "admin/orders.lazy.tsx"
    },
    "/admin/policy": {
      "filePath": "admin/policy.lazy.tsx"
    },
    "/admin/products": {
      "filePath": "admin/products.lazy.tsx"
    },
    "/admin/settings": {
      "filePath": "admin/settings.lazy.tsx"
    },
    "/admin/task": {
      "filePath": "admin/task.lazy.tsx"
    },
    "/admin/idols/$teamId": {
      "filePath": "admin/idols.$teamId.lazy.tsx"
    },
    "/admin/stores/$storeId": {
      "filePath": "admin/stores.$storeId.lazy.tsx"
    },
    "/admin/users/$userId": {
      "filePath": "admin/users.$userId.lazy.tsx"
    },
    "/admin/idols/": {
      "filePath": "admin/idols.index.tsx"
    },
    "/admin/stores/": {
      "filePath": "admin/stores.index.lazy.tsx"
    },
    "/admin/users/": {
      "filePath": "admin/users.index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
